- name: Setup Rocky Server
  hosts: server_role_rocky_server
  become: true
  vars: 
    ansible_user: rocky
    ansible_ssh_private_key_file: /home/laraa/.ssh/aws
  roles:
    - rocky

- name: Setup Debian Server
  hosts: server_role_debian_server
  become: true
  roles:
    - debian
  vars:
    ansible_user: debian
    ansible_ssh_private_key_file: /home/laraa/.ssh/aws
