- name: Setup Rocky Server
  hosts: server_role_rocky_server
  become: true
  vars: 
    ansible_user: rocky
  roles:
    - rocky

- name: Setup Debian Server
  hosts: server_role_debian_server
  become: true
  vars: 
    ansible_user: debian
  roles:
    - debian
